language: python
python:
 - "3.7"
install:
- pip install coverage
script:
 - coverage run -m unittest discover
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "Encrypted <access-key-id>=placeholder"
  secret_access_key:
    secure: "Encypted <secret-access-key>=placeholder"
  region: "us-east-1"
  app: "index"
  env: "project-dev"
  bucket_name: "elasticbeanstalk-us-east-1-595465365205"
  on:
    branch: master 
